version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=nyc_data
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    command: ["npm", "start"]

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nyc_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
